language: node_js
node_js: '10'
dist: trusty
sudo: false
git:
  depth: 1
env:
  global:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - CLOUDSDK_PYTHON_SITEPACKAGES=1
  - GAE_APP_ID=ebidel-dd868
cache:
  yarn: true
  directories:
  - node_modules
install:
- yarn
script:
- yarn lint
- yarn build
after_success:
- "./travis/deploy_pr_gae.sh"
- npm run lh -- --perf=100 --a11y=100 --bp=100 --seo=100 $LH_TEST_URL
